management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
